# Generated by Django 3.2 on 2022-06-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('adapter', models.CharField(choices=[('Fixer', 'Fixer'), ('Mock Application', 'Mock Application')], max_length=20)),
                ('name', models.CharField(db_index=True, max_length=140)),
                ('priority', models.PositiveIntegerField(db_index=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
